### ISSUE TITLE
"/fe clean" gives an error

### ISSUE THREAD

**Issue by WoAnerges** [niccholaspage/Fe#21]
issued server command: /fe clean
22:52:11 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'fe' in plugin Fe v0.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:546)
        at net.minecraft.server.v1_5_R3.PlayerConnection.handleCommand(PlayerConnection.java:985)
        at net.minecraft.server.v1_5_R3.PlayerConnection.chat(PlayerConnection.java:901)
        at net.minecraft.server.v1_5_R3.PlayerConnection.a(PlayerConnection.java:846)
        at net.minecraft.server.v1_5_R3.Packet3Chat.handle(Packet3Chat.java:44)
        at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:215)
        at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java:115)
        at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
        at org.spigotmc.MultiplexingServerConnection.b(MultiplexingServerConnection.java:72)
        at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:583)
        at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:227)
        at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:472)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:404)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 6
        at java.lang.String.substring(String.java:1907)
        at org.melonbrew.fe.SQLibrary.Database.getStatement(Database.java:163)
        at org.melonbrew.fe.SQLibrary.MySQL.query(MySQL.java:109)
        at org.melonbrew.fe.database.databases.SQLDB.clean(SQLDB.java:234)
        at org.melonbrew.fe.API.clean(API.java:141)
        at org.melonbrew.fe.command.commands.CleanCommand.onCommand(CleanCommand.java:20)
        at org.melonbrew.fe.FeCommand.onCommand(FeCommand.java:125)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        ... 15 more

**Comment by niccholaspage** [comment]
Fixed in dev build.
