### ISSUE TITLE
AbstractMethodError with Vault

### ISSUE THREAD

**Issue by snowgears** [niccholaspage/Fe#70]
Writing a shop plugin that hooks into vault. I installed FeEconomy onto my server to test an economy plugin. I simply use the vault deposit player method and your plugin throws this error.

Caused by: java.lang.AbstractMethodError: org.melonbrew.fe.Economy_Fe.depositPlayer(Lorg/bukkit/OfflinePlayer;D)Lnet/milkbowl/vault/economy/EconomyResponse;
    at com.snowgears.shop.listeners.ExchangeListener.playerSellToShop(ExchangeListener.java:234) ~[?:?]
    at com.snowgears.shop.listeners.ExchangeListener.onShopSignClick(ExchangeListener.java:51) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_67]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_67]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_67]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
    ... 17 more

**Comment by snowgears** [comment]
Also, I tried replacing Fe Economy with iConomy and it works perfectly
